Based on the synthesis of IIT and GWT principles, augmented with concepts from modern AI and complex systems, the CQICS architecture comprises the following core components:
    2. Core Components:
        ◦ Specialized Modules (SMs): These are analogous to GWT's processors.10 They represent distinct computational units responsible for specific functions (e.g., visual processing, auditory analysis, linguistic parsing, logical inference, motor control, memory access). SMs can be implemented using diverse AI techniques, including deep neural networks, symbolic reasoning engines, or hybrid neurosymbolic systems.5 They operate largely in parallel and unconsciously.
        ◦ Global Workspace (GW): This component embodies the central information exchange hub of GWT.10 It is a dynamic, limited-capacity representational space where information from selected SMs becomes globally available via broadcasting. Implementation could involve shared latent spaces trained via cycle consistency 38, dynamically updated knowledge graphs serving as a structured workspace 5, or other mechanisms capable of integrating and disseminating information across the system. It incorporates attentional mechanisms to regulate access.
        ◦ Causal Structure Analyzer (CSA): This is the core IIT-inspired component, unique to the CQICS architecture. Its function is to analyze the causal interactions and transition probabilities among the system's components (SMs, GW, and their connections) based on IIT's postulates.6 The CSA aims to identify potential "complexes" (maximally irreducible substrates) within the system and estimate their integrated information (Φ) or related structural properties. Given the computational challenges 6, the CSA might employ approximations or heuristics.
        ◦ Grounding Interface (GI): This crucial interface connects the internal representations and dynamics of the CQICS system to the external world or validated knowledge sources. It handles sensory data input, translates internal decisions into actions (via effectors), and links internal symbols or representations to external referents (e.g., objects in the environment, entries in a knowledge base).5 This component is essential for addressing the symbol grounding problem 2 and enabling meaningful interaction, drawing inspiration from digital twin technologies 31 and neurosymbolic grounding techniques.5
        ◦ Metacognitive Controller (MC): This component provides high-level oversight and control, analogous to executive functions associated with GWT 11 and metacognitive layers in NesyAI.5 It can exert top-down attentional control on the GW 38, allocate computational resources to SMs, and potentially utilize outputs from the CSA (e.g., Φ estimates, structural analyses) and the GI (e.g., error signals, environmental feedback) to guide learning, adaptation, or strategic processing.
    3. Information Dynamics:
        ◦ Parallel Processing & Competition: SMs process inputs concurrently. Based on bottom-up factors (e.g., stimulus intensity, novelty) and top-down signals from the MC reflecting goals or context, SMs compete for access to the limited-capacity GW.10
        ◦ Broadcasting & Integration: The information ("content") from the winning SM(s) enters the GW and is broadcast to all other SMs.10 This global dissemination facilitates information integration, enabling coordinated responses and allowing diverse modules to contribute to solving complex problems.10 This broadcast process is hypothesized to be a primary driver of the system's functional integration, potentially correlating with the structural integration measured by the CSA.
        ◦ Causal Analysis: The CSA operates continuously or periodically, analyzing the system's state transitions and interaction patterns. It computes (or approximates) measures like Φ and identifies the dominant cause-effect structure (Φ-structure) based on IIT principles.8
        ◦ Feedback Loops: The system incorporates multiple feedback loops. The GI provides feedback from the environment (sensory input, consequences of actions). The CSA provides feedback about the system's internal structural properties (e.g., level of integration, complexity). These feedback signals inform the MC, which can then adjust attentional priorities, resource allocation, or learning parameters, creating adaptive behavior.
Bridging IIT/GWT Computationally: The proposed architecture attempts a computational reconciliation between IIT and GWT. IIT mandates a comprehensive analysis of the system's causal structure to identify the complex and its Φ-structure 8, a computationally demanding task.6 GWT proposes a functionally limited workspace.11 The CQICS architecture bridges this via the CSA and GW. The CSA performs the IIT-based analysis, potentially using approximations. The GW does not represent the entire Φ-structure but rather the outcome of attentional selection operating on information streams whose underlying integration and causal significance are assessed (at least implicitly) by the CSA and MC. The content broadcast from the GW then influences the states of the SMs, thereby altering the overall system state and providing new input for the subsequent analysis cycle by the CSA. This creates a dynamic loop where the system's functional state (GW content) reflects aspects of its underlying causal structure (analyzed by CSA), and the functional operations (broadcasting) actively shape that structure over time.
